/**
 * @fileoverview Data Transfer Object (DTO) defining the response shape for the
 * auction state catch-up endpoint: GET /auction/{id}/state.
 *
 * This DTO is used when a client first loads the page or reconnects to the
 * WebSocket stream, providing a synchronous "what is the current state right now?"
 * answer before the real-time stream begins. This prevents the client from
 * displaying stale or empty state while awaiting the next WebSocket push.
 */

export class AuctionStateDto {
  /** The UUID of the auction product being queried. */
  item_id: string;

  /** The current leading monetary bid recognized by the platform. */
  current_price: number;

  /**
   * The user ID of the person who currently holds the highest bid.
   * Will be null/undefined if no bids have been placed yet.
   */
  highest_bidder_id?: string;

  /** The product name, helpful for the client to confirm they are viewing the right item. */
  name: string;

  /** ISO 8601 timestamp of when this state snapshot was generated by the server. */
  snapshot_at: string;
}
